development:
  adapter: mysql2
  encoding: utf8
  database: bitcoin-bank_development
  username: rails
  password: rails

test:
  adapter: mysql2
  encoding: utf8
  database: bitcoin-bank_test
  username: rails
  password: rails
